#!/bin/sh
#
# fluxbox startup-script:
#
# Lines starting with a '#' are ignored.


# Applications you want to run with fluxbox.
# MAKE SURE THAT APPS THAT KEEP RUNNING HAVE AN ''&'' AT THE END.
#
# unclutter -idle 2 &
# wmnd &
# wmsmixer -w &
# idesk &
#
# Debian-local change:
#   - fbautostart has been added with a quick hack to check to see if it
#     exists. If it does, we'll start it up by default.
which fbautostart > /dev/null
if [ $? -eq 0 ]; then
    fbautostart
fi

/home/armandito/programas/bash/auto_randr.sh &
nm-applet &
workrave &
exec fluxbox

fbsetbg $HOME/.fluxbox/wallpaper.jpg
# or if you want to keep a log:
# exec fluxbox -log "/home/armandito/.fluxbox/log"

